<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>VarelaAloisio.HealthSystem.Runtime</AssemblyName>
    <RootNamespace>HealthSystem</RootNamespace>
    <LangVersion>7</LangVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <AssemblyCompany>VarelaAloisio</AssemblyCompany>
    <AssemblyProduct>HealthSystem</AssemblyProduct>
    <Copyright>Copyright © 2021</Copyright>
  </PropertyGroup>
  <Target Name="CopyOutputToUnityPackage" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\..\UnityPackage-Project\Assets\Runtime" />
    <Copy SourceFiles="$(TargetPath);$(TargetDir)$(TargetName).pdb"
          DestinationFolder="$(MSBuildProjectDirectory)\..\..\UnityPackage-Project\Assets\Runtime" />
  </Target>
</Project>