name: .NET Framework CI

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore LS.sln

    - name: Build
      run: msbuild /p:Configuration=Release LS.sln

    - name: Test
      run: |
        Install-Package NUnit.Console -Version 3.11.1
        nunit3-console LS.UnitTests/bin/Release/LS.UnitTests.dll

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload .dll file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LS/bin/Release/LS.dll
        asset_name: LS.dll
        asset_content_type: application/octet-stream

    - name: Upload .pdb file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LS/bin/Release/LS.pdb
        asset_name: LS.pdb
        asset_content_type: application/octet-stream