name: TestPR

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]

jobs:
  BuildPR:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      
    - name: Cache NuGet packages
      uses: actions/cache@v3.3.2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore Projects/HealthSystem.sln

    - name: Build
      run: msbuild /p:Configuration=Release Projects/HealthSystem.sln

  TestPR:
    needs: [BuildPR]
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Run Tests
      run: |
        nuget install NUnit.ConsoleRunner -Version 3.11.1
        ./NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe Projects/HealthSystem.UnitTests/bin/Release/HealthSystem.UnitTests.dll
